name: Build App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tres-en-raya

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tres-en-raya/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Construir proyecto con Vite
        run: npm run build