name: Build App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 2doParcial/Class17/tres-en-raya

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm ci

      - name: Construir proyecto con Vite
        run: npm run build

      - name: Guardar ZIP
        uses: actions/upload-artifact@v4
        with:
          name: aplicacion-web
          path: 2doParcial/Class17/tres-en-raya/dist